### ISSUE TITLE
gzipDecode error: Uncaught RangeError: offset is out of bounds

### ISSUE THREAD

**Issue by mbykovskyy** [manyuanrong/wasm_gzip#1]
I'm not sure if the issue is with this library or the Deno internals. I decode thousands of gzip encoded blobs in a loop, by calling `gzipDecode`.

```
for await (const serp of readCSVObjects(f)) {
    const res = await fetch(url)
    const body = new Uint8Array(await res.arrayBuffer())
    const html = gzipDecode(body)
    await Deno.writeFile(dest, html)
}
```

Over time `gzipDecode` fails with the following error.

```
error: Uncaught RangeError: offset is out of bounds
  getUint8Memory0().set(arg, ptr / 1);
                    ^
    at Uint8Array.set (<anonymous>)
    at passArray8ToWasm0 (https://raw.githubusercontent.com/manyuanrong/wasm_gzip/master/wasm.js:18:21)
    at gzip_decode (https://raw.githubusercontent.com/manyuanrong/wasm_gzip/master/wasm.js:42:14)
    at gzipDecode (mod.ts:7:10)
```

I checked the gz blob and it was valid. I.e. I was able to decode it successfully with other tools.

**Comment by manyuanrong** [comment]
Can you provide the smallest sample code that failed? So that I can locate the problem
